name: deploy bot-dispatch

on:
  workflow_dispatch:
  push:
    branches:
      - ci/*
      - feat/*
      - fix/*

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: write to wrangler config file
        shell: bash
        run: |
          cd ./
          touch wrangler.jsonc
          echo ${{ secrets.WRANGLER_CONFIG }} > wrangler.jsonc

      - name: run tests
        shell: bash
        run: |
          npm install
          npm run test
