name: deploy bot-dispatch

on:
  workflow_dispatch:
  push:
    branches:
      - ci/*
      - feat/*
      - fix/*

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: write to wrangler config file
        shell: bash
        run: |
          cd ./
          touch wrangler.jsonc
          echo ${{ secrets.WRANGLER_CONFIG }} > wrangler.jsonc

      - name: run tests
        shell: bash
        run: |
          npm install
          npm run test

      - name: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy > /dev/null 2>&1
          secrets: |
            API_KEY
        env:
          API_KEY: ${{ secrets.API_KEY }}
